# Generated by Django 4.2.16 on 2024-10-14 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 14, 14, 17, 0, 234920)),
        ),
    ]
