# Generated by Django 4.2.16 on 2024-12-07 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_client_alter_category_name_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 1, 49, 56, 87625)),
        ),
    ]
