# Generated by Django 4.2.16 on 2024-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='ship_address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='ship_address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='ship_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='ship_country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='ship_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='ship_full_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='ship_state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='full_name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ship_zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
